// <auto-generated />
namespace LibrarySystem99.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AddFineAndBorrowingPolicy : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddFineAndBorrowingPolicy));
        
        string IMigrationMetadata.Id
        {
            get { return "202605121406594_AddFineAndBorrowingPolicy"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
